### ISSUE TITLE
Good practice when creating constraints

### ISSUE THREAD

**Issue by willu47** [PyPSA/linopy#110]
I am considering how to structure my code into modular blocks so that I can better test each aspect of model creation using linopy.

At present, I create a whole bunch of Variables and assign the Variable to a Python variable e.g.
```python
new_capacity = m.add_variables(lower=0, upper=inf, coords=coords, name='NewCapacity', integer=False)
```
Ideally, I'd like to put all the variable creation in a function:
```python
def add_variables(m: Model) -> Model:
    m.add_variables(lower=0, upper=inf, coords=coords, name='NewCapacity', integer=False)
    return m
```
Now I can access my variables like so `m['NewCapacity']`.

When adding constraints, is there a preference between the following alternatives?

First with Variables stored in variables:
```python
accumulated_new_capacity = m['AccumulatedNewCapacity']
new_capacity = m['NewCapacity']
def bounds(model, r, t, y):
    return accumulated_new_capacity[r,t,y] - 1 * \
                sum(new_capacity[r,t,yy] for yy in ds.coords['YEAR'].values 
                    if (y-yy >= 0) and (y-yy < ds['OperationalLife'].sel({'REGION':r, 'TECHNOLOGY': t}))) == 0
    
c_aa1_total_new_capacity = m.add_constraints(bounds, coords=RTeY, name='CAa1_TotalNewCapacity')
```
versus second option with access to Variable in the function
```python
def bounds(model, r, t, y):
    return m['AccumulatedNewCapacity'][r,t,y] - 1 * \
                sum(m['NewCapacity'][r,t,yy] for yy in ds.coords['YEAR'].values 
                    if (y-yy >= 0) and (y-yy < ds['OperationalLife'].sel({'REGION':r, 'TECHNOLOGY': t}))) == 0
    
c_aa1_total_new_capacity = m.add_constraints(bounds, coords=RTeY, name='CAa1_TotalNewCapacity')
```
Or is there no difference that is relevant?

**Comment by FabianHofmann** [comment]
Hey @willu47! Nice to see you here :) Thanks for the issue. I'll be back from my holiday tomorrow, then I can properly answer (also the other issues you raised)

**Comment by FabianHofmann** [comment]
So, actually there is no functional difference between the two options. In this case it boils down to readability, I would vote for the second options, as `accumulated_new_capacity` and `new_capacity` are not yet defined in the workflow (if they were, then the first options is more readable). 

Generally, as pointed out in #108, it is preferable to build constraints with array based operations, that are avoiding a `bounds` function. The reason is that array based operations are parallelized, while passing a function to `add_constraints` / `linexpr` iterates over all combinations of indexes and therefore can be much slower. 

I think generally I need to improve the doc a bit further and give more examples for good practise. If you have some thoughts, what was difficult / unclear in particular, do not hesitate to give feedback.

**Comment by willu47** [comment]
Many thanks for this explanation.  What is particularly difficult moving from MathProg and Pyomo, is understanding how to reformulate the function approach into arrays and masks.  The answer you gave in #108 is really great - if you could show step-by-step how to convert the conditions into a mask, and then convert the function to an array-based approach it could really help.

The current examples for constructing constraints in the documentation are very simple - there are no summations over indices and no conditions, so including more examples like this would be helpful for others in a similar position to me.
