### ISSUE TITLE
Implement cumsum of Variables

### ISSUE THREAD

**Issue by hblunck** [PyPSA/linopy#145]
For many optimization models that consider time, it would be helpful to be able have a shortcum to calcualte the cumulated sum along a dimension (e.g. to calculate the inventory position as the cumulated sum of all inbound orders minus demand).

This functionalty is available in xarray but apparently not in linopy (as of Version 0.2.2).

**Comment by hblunck** [comment]
A walkaround right now is to use the `rolling` method and then call `.sum()` on the result
> inventory_position.rolling(time=10000).sum()
(where 10000 is just a large number, can be longer than the size of the dimension)

**Comment by FabianHofmann** [comment]
Hey @hblunck, this would actually be a nice feature. Since the formulation is quite similar, your approach might even fit for the final function by setting the window size to the size of the dimension. I am not sure about the performance, but anyway this could suit for a start. Would you be interested in drafting a PR?

**Comment by hblunck** [comment]
Hey @FabianHofmann , thanks for the encouraging feedback. I did take a shot at it in #147. I don't think that is complete yet, though.
