### ISSUE TITLE
Support MOSEK

### ISSUE THREAD

**Issue by fneum** [PyPSA/linopy#35]
feature requested on PyPSA mailing list

https://www.mosek.com/

https://docs.mosek.com/10.0/cmdtools.pdf

**Comment by loongmxbt** [comment]
Upvote+1. I've found that Mosek has the lowest price among commercial solvers.
Pyomo+Mosek10 has some problems in getting dual values. Need to test if mosek is able to get duals.

**Comment by bkprejac** [comment]
> Upvote+1. I've found that Mosek has the lowest price among commercial solvers.
> Pyomo+Mosek10 has some problems in getting dual values. Need to test if mosek is able to get duals.
> https://docs.mosek.com/latest/pythonapi/accessing-solution.html

Hi. How did you use it with mosek? With pyomo or without? Is it possible to share a branch? I am new with pypsa, but I am a mosek user, and would like to try it..

**Comment by loongmxbt** [comment]
@bkprejac Hi, I use Mosek with pyomo. And when it comes to MILP problems, after pyomo fix binary variables and recalculate, pyomo still raises warning 'WARNING: Cannot get duals for MIP' and cannot get dual value afterwards.
I know the reason is related to the integer variables inside the model. But I cannot find a way to remove those variables. Seems pyomo fix() just add constraints to them.
I check solvers like cbc and cplex, with fix() and second calculation, they'll just do fine.

**Comment by fneum** [comment]
closed by #189
